### ISSUE TITLE
Returning wrong packet while removing the shared music

### ISSUE THREAD

**Issue by valid22** [Kits-une/Kitsune#5]
Reg: <a href="https://github.com/Kits-une/Kitsune/blob/sound-studio/Kitsune/ClubPenguin/Handlers/Play/Music.php#L127">Music.php</a>

If client sends "Share" request, this is what you need to return
```
$penguin->send("%xt%sharemymusictrack%-1%1%");
```
else if the penguin sends "Remove Share" request, this is what you need to return
```
%xt%sharemymusictrack%-1%1%$track_id|0%
```
Else the client won't recognize the received packet correctly and may not act properly.

This is verified from going through the AS Files of Sound Studio.

**Comment by TunnelBlanket** [comment]
Just logged in to Club Penguin to check, and it's what the client sends.
```
%xt%s%musictrack#sharemymusictrack%6%11604294%0%
%xt%sharemymusictrack%-1%1%
```
