### ISSUE TITLE
Igloo will not load | infinite loading loop

### ISSUE THREAD

**Issue by WindowsTV** [Kits-une/Kitsune#6]
At first I thought it was because the SWFs were missing from the as3 media server then I added them. Igloos still wont load.

When I click my player's igloo it gets stuck on an infinite loading loop.

http://prntscr.com/9xbf4k - Here is a photo of kitsune running.

**Comment by TunnelBlanket** [comment]
Are you still experiencing this issue? If so, do you think you could send me a more complete version of the server's output without the notices?

**Comment by WindowsTV** [comment]
I no longer am, it was my Database's fault and me not realizing it lol. Thank you for looking into this problem and sorry for the innocence. Though I am having an issue with the Care Inventory in the igloo the sleep interaction wont work and I do not see a packet sent for it

**Comment by nikerocks100** [comment]
I am experiencing infinite igloo loading.. Please help me out
