### ISSUE TITLE
Friend Requests Don't Send / Ignores don't work

### ISSUE THREAD

**Issue by tootyta** [Kits-une/Kitsune#7]
When you send a friend request with this KitSune source, it literally will just not get to other player. It gives this error: http://prntscr.com/9zzr5q . With Ignores, when you try to ignore someone, they will disappear from the room... But if they re-enter the room, they will appear again, showing that they have not been successfully ignored. And there name doesn't appear on the ignored people list. It doesn't show an error.

**Comment by TunnelBlanket** [comment]
Unless you're using an extremely out-dated version of Club Penguin's client, you shouldn't be receiving those packets as Club Penguin's buddy system is now handled by a standalone XMPP server.

If you've modified your client to use the old buddy system (which I believe still (partially) exists), you can try asking for help at https://solero.me, but we (the Kitsune team) won't support you as it's no longer used by Club Penguin.

**Comment by WindowsTV** [comment]
I have a question about the Friend Requests, the client I use is from the first Frozen Party which has the new CSS/HTML Friends List,  would I get this error when trying to send a friend request? And this "handled by a standalone XMPP server." How can this be set up to use the new Friend's List?

Also Ignore makes the player completely invisible. When the server adds the player and it tells the user ignored them the client hides them from the room.

**Comment by TunnelBlanket** [comment]
You will not receive this error if you're using the new friends list. In order to get the new friends list to work, you'll need to set up an XMPP server, such as [Tigase](https://projects.tigase.org/projects/tigase-server). You'll also probably need to modify the play page, so that the friends list connects to your server. I don't have any specific information on how to do it though, so you're on your own.

**Comment by WindowsTV** [comment]
Alright I'll give this ago! Do you happen to know how I can download the friends list? I have the files from the play page but it dose not seem to open, I feel like I downloaded it wrong o:

**Comment by DeerBlue** [comment]
i think did it 
http://prntscr.com/a4ybii

**Comment by DeerBlue** [comment]
Arthur you can make a tutorial how fix play page ,the friend list files don't need modifications

**Comment by TunnelBlanket** [comment]
I haven't been able to get the friends list to work myself, so I will not make a tutorial.
