### ISSUE TITLE
Brocasting & Likes isn't working

### ISSUE THREAD

**Issue by DeerBlue** [Kits-une/Kitsune#8]
in the brocadcasting i get
Notice: Undefined index: Wolf in C:\xampp\htdocs\Kitsune [AS3]\Kitsune\ClubPenguin\Handlers\Play\Music.php on line 59

---

if i like again ,the handler doesnt send %xt%liketrack%6%101%1%0% when can't like to the track ,and the peoples think are liking two times

**Comment by DeerBlue** [comment]
also

07:45:58 [Debug] > Received %xt%s%musictrack#canliketrack%4%101%2%

Warning: array_key_exists() expects parameter 2 to be array, null given in C:\xampp\htdocs\Source [AS3]\Kitsune\ClubPenguin\Handlers\Play\Music.php on line 41
07:45:58 [Debug] > Outgoing: %xt%canliketrack%-1%2%1%
07:45:58 [Debug] > Received %xt%s%musictrack#canliketrack%4%101%2%

**Comment by TunnelBlanket** [comment]
It looks like you're missing the `tracks` table in your database. Run the following query to create it
```sql
CREATE TABLE `tracks` (
  `ID` int(10) UNSIGNED NOT NULL,
  `Name` varchar(12) COLLATE utf8mb4_unicode_ci NOT NULL,
  `Owner` int(10) UNSIGNED NOT NULL,
  `Hash` char(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `Sharing` tinyint(1) NOT NULL DEFAULT '0',
  `Pattern` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `Likes` smallint(5) UNSIGNED NOT NULL DEFAULT '0',
  `LikeStatistics` text COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `tracks`
  MODIFY `ID` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;
```
